name: FTP Deploy

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.bettaniseries.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # server-dir: /trust.nebosh-azurewebsites.com/
        local-dir: ./ # Adjust as necessary
        server-dir: /  # Updated path
        state-name: .ftp-deploy-sync-state.json 
        exclude: |
            **/vendor/**
            **/node_modules/**
            .env
            **/.git/**
